// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderRice.Data;

namespace OrderRice.Migrations
{
    [DbContext(typeof(OrderRiceContext))]
    [Migration("20210515022814_OrderRiceMigration")]
    partial class OrderRiceMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("OrderRice.Model.Dish", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Userid")
                        .HasColumnType("TEXT");

                    b.Property<int>("gia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("OrderRice.Model.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.Property<int>("tienDaNhan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tongTien")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OrderRice.Model.Dish", b =>
                {
                    b.HasOne("OrderRice.Model.User", null)
                        .WithMany("dishs")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("OrderRice.Model.User", b =>
                {
                    b.Navigation("dishs");
                });
#pragma warning restore 612, 618
        }
    }
}
