// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderRice.Data;

namespace OrderRice.Migrations
{
    [DbContext(typeof(OrderRiceContext))]
    [Migration("20210517075501_OrderRiceMigration")]
    partial class OrderRiceMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("DishUser", b =>
                {
                    b.Property<string>("dishsid")
                        .HasColumnType("TEXT");

                    b.Property<string>("usersid")
                        .HasColumnType("TEXT");

                    b.HasKey("dishsid", "usersid");

                    b.HasIndex("usersid");

                    b.ToTable("DishUser");
                });

            modelBuilder.Entity("OrderRice.Model.Dish", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int>("gia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("giaDoAn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("OrderRice.Model.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.Property<int>("tienDaNhan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tongTien")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DishUser", b =>
                {
                    b.HasOne("OrderRice.Model.Dish", null)
                        .WithMany()
                        .HasForeignKey("dishsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderRice.Model.User", null)
                        .WithMany()
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
